#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.Globalization;
using UnityEditor;
using UnityEditorInternal;
using UnityEngine;

namespace BlenderSyncVNext.Localization
{
    public enum BlenderSyncLanguage
    {
        System = 0,
        English = 1,
        SimplifiedChinese = 2,
    }

    public static class BlenderSyncLocalization
    {
        private const string LanguageEditorPrefKey = "BlenderSyncVNext.Language";

        private static readonly IReadOnlyDictionary<string, string> SimplifiedChinese =
            new Dictionary<string, string>(StringComparer.Ordinal)
            {
                { "TriSync is available only in Edit Mode.", "TriSync 仅在编辑模式下可用。" },
                { "System", "跟随系统" },
                { "English", "English" },
                { "Simplified Chinese", "简体中文" },
                { "Language", "语言" },
                { "Settings", "设置" },
                { "Transform Smoothing", "变换平滑" },
                { "Smooth automatically synchronized object transforms in the Unity editor.", "在 Unity 编辑器中平滑自动同步的对象变换。" },
                { "Smoothing Time", "平滑时间" },
                { "Time in seconds used to settle on the latest synchronized transform.", "到达最新同步变换所用的时间（秒）。" },
                { "Follow Curve", "跟随曲线" },
                { "Normalized follow progress over the smoothing time.", "平滑时间内的归一化跟随进度。" },
                { "Reset Smoothing", "重置平滑设置" },
                { "TriSync", "TriSync" },
                { "Session", "会话" },
                { "Registry", "注册表" },
                { "Diagnostics", "诊断" },
                { "Connected", "已连接" },
                { "Connecting", "正在连接" },
                { "Disconnected", "未连接" },
                { "Error", "错误" },
                { "Protocol mismatch", "协议不匹配" },
                { "Connection error", "连接错误" },
                { "Ready to connect", "可以连接" },
                { "Waiting for handshake", "等待握手" },
                { "Session ready", "会话已就绪" },
                { "Update the other endpoint", "请更新另一端" },
                { "See Diagnostics", "请查看诊断" },
                { "Connect", "连接" },
                { "Disconnect", "断开连接" },
                { "Port", "端口" },
                { "Must match the Blender listener port.", "必须与 Blender 监听端口一致。" },
                { "Blender application version reported by the connected endpoint.", "已连接端点报告的 Blender 应用版本。" },
                { "Send To Blender", "发送到 Blender" },
                { "Meshes", "网格" },
                { "Use + to add a Mesh asset or mesh-bearing GameObject.", "使用 + 添加网格资源或包含网格的 GameObject。" },
                { "Creating...", "正在创建..." },
                { "Create Mesh in Blender", "在 Blender 中创建网格" },
                { "That Mesh is already in the list.", "该网格已在列表中。" },
                { "Select a Mesh or a GameObject with a MeshFilter or SkinnedMeshRenderer.", "请选择网格，或包含 MeshFilter / SkinnedMeshRenderer 的 GameObject。" },
                { "Only Mesh assets and mesh-bearing GameObjects can be added.", "只能添加网格资源或包含网格的 GameObject。" },
                { "GameObject '{0}' has no MeshFilter or SkinnedMeshRenderer shared Mesh.", "GameObject“{0}”没有 MeshFilter 或 SkinnedMeshRenderer 的共享网格。" },
                { "Last creation", "最近创建" },
                { "Details ({0})", "详情（{0}）" },
                { "Last activity", "最近活动" },
                { "Protocol", "协议" },
                { "Features", "功能" },
                { "Last error", "最近错误" },
                { "Created {0} object in Blender.", "已在 Blender 中创建 {0} 个对象。" },
                { "Created {0} objects in Blender.", "已在 Blender 中创建 {0} 个对象。" },
                { "Created {0} objects; {1} skipped.", "已创建 {0} 个对象；跳过 {1} 个。" },
                { "Add a compatible Mesh to create in Blender.", "请添加可在 Blender 中创建的兼容网格。" },
                { "Blender did not report a creation result.", "Blender 未报告创建结果。" },
                { "Connect to Blender before creating a mesh.", "请先连接 Blender，再创建网格。" },
                { "No compatible mesh could be exported.", "没有可导出的兼容网格。" },
                { "Add at least one Mesh before creating it in Blender.", "在 Blender 中创建前，请至少添加一个网格。" },
                { "The mesh snapshot could not be sent to Blender.", "无法将网格快照发送到 Blender。" },
                { "The staged mesh snapshot could not be sent to Blender.", "无法将暂存的网格快照发送到 Blender。" },
                { "Sent to Blender. This Blender version does not report creation results.", "已发送到 Blender。此 Blender 版本不会报告创建结果。" },
                { "Blender did not confirm mesh creation within 30 seconds. It may still finish.", "Blender 未在 30 秒内确认网格创建；操作仍可能完成。" },
                { "Preparing queued mesh data...", "正在准备队列中的网格数据..." },
                { "Waiting for Blender to create the mesh...", "等待 Blender 创建网格..." },
                { "Queued in Blender.", "已在 Blender 中排队。" },
                { "Blender could not create the queued mesh.", "Blender 无法创建队列中的网格。" },
                { "No creation result is available.", "没有可用的创建结果。" },
                { "No activity", "暂无活动" },
                { "Legacy", "旧版" },
                { "Not negotiated", "未协商" },
                { "None", "无" },
                { "Creates new Blender Mesh objects from the queued readable Meshes.\nSupports UV0-UV7 and single-frame BlendShapes.\nRigging, current deformation, multi-frame BlendShapes, and reverse sync are not included.", "使用队列中可读的网格创建新的 Blender 网格对象。\n支持 UV0-UV7 和单帧 BlendShape。\n不包含骨骼绑定、当前形变、多帧 BlendShape 和反向同步。" },
                { "Technical Details", "技术详情" },
                { "Logging", "日志" },
                { "Verbose Logging", "详细日志" },
                { "Pipeline", "管线" },
                { "Copy Diagnostics", "复制诊断信息" },
                { "Copied", "已复制" },
                { "Clear", "清除" },
                { "Recent Activity", "最近活动" },
                { "No activity recorded.", "暂无活动记录。" },
                { "Showing latest {0} of {1}.", "显示最近 {0} 条，共 {1} 条。" },
                { "Last refresh", "最近刷新" },
                { "Refresh error", "刷新错误" },
                { "Asset pipeline", "资源管线" },
                { "Object pipeline", "对象管线" },
                { "Asset error", "资源错误" },
                { "Object error", "对象错误" },
                { "Auto Refresh", "自动刷新" },
                { "Refresh", "刷新" },
                { "Resources", "资源" },
                { "Objects", "对象" },
                { "No resource records yet. Import objects from Blender first.", "暂无资源记录。请先从 Blender 导入对象。" },
                { "No object binding records yet. Import objects from Blender first.", "暂无对象绑定记录。请先从 Blender 导入对象。" },
                { "No resource records found for current filter.", "当前筛选条件下没有资源记录。" },
                { "No object records found for current filter.", "当前筛选条件下没有对象记录。" },
                { "Showing {0} / {1}", "显示 {0} / {1}" },
                { "{0} total, {1} mapped, {2} issues", "共 {0} 个，已映射 {1} 个，问题 {2} 个" },
                { "{0} total, {1} bound, {2} issues", "共 {0} 个，已绑定 {1} 个，问题 {2} 个" },
                { "Asset queue", "资源队列" },
                { "Object queue", "对象队列" },
                { "Processing", "处理中" },
                { "Pending", "等待中" },
                { "Idle", "空闲" },
                { "{0} pending", "{0} 个等待中" },
                { "{0} failed", "{0} 个失败" },
                { "Type", "类型" },
                { "Search", "搜索" },
                { "Bound only", "仅已绑定" },
                { "All", "全部" },
                { "Mesh", "网格" },
                { "Material", "材质" },
                { "Texture", "纹理" },
                { "Scene Object", "场景对象" },
                { "Object", "对象" },
                { "Rigged Object", "骨骼对象" },
                { "Unregister...", "注销..." },
                { "Unregister Mode", "注销模式" },
                { "Selected: resources={0} objects={1}", "已选择：资源={0} 对象={1}" },
                { "Unregister Selected", "注销所选项" },
                { "Cancel", "取消" },
                { "No referenced assets recorded.", "未记录被引用的资源。" },
                { "No object or material references recorded.", "未记录对象或材质引用。" },
                { "No material slots recorded.", "未记录材质槽。" },
                { "No material references recorded.", "未记录材质引用。" },
                { "References", "引用" },
                { "Referenced By", "被引用关系" },
                { "Referenced Assets", "引用的资源" },
                { "Material Texture: {0}", "材质纹理：{0}" },
                { "Rigged: {0}", "骨骼对象：{0}" },
                { "Material[{0}]", "材质[{0}]" },
                { "Mesh[{0}]", "网格[{0}]" },
                { "Texture: {0}", "纹理：{0}" },
                { "Managed Instance", "托管实例" },
                { "(slot)", "（槽位）" },
                { "Referenced by Objects", "被对象引用" },
                { "Referenced by Materials", "被材质引用" },
                { "Mesh Asset", "网格资源" },
                { "Prefab", "预制体" },
                { "Character", "角色" },
                { "Animator", "Animator" },
                { "Avatar", "Avatar" },
                { "Root Node", "根节点" },
                { "Character Animator used to build and receive the Generic Avatar.", "用于构建并接收 Generic Avatar 的角色 Animator。" },
                { "Transform whose local position and rotation curves become Animator RootT and RootQ curves.", "其局部位置和旋转曲线将转换为 Animator RootT 与 RootQ 曲线的 Transform。" },
                { "Avatar assigned to the selected Animator.", "指定给所选 Animator 的 Avatar。" },
                { "Create and assign a Generic Avatar using the selected Root Node.", "使用所选根节点创建并指定 Generic Avatar。" },
                { "Root Node must be the Animator transform or one of its children.", "根节点必须是 Animator Transform 或其子级。" },
                { "Source Clip", "源动画片段" },
                { "Clip", "片段" },
                { "Raw Generic clip to copy and augment with Animator RootT and RootQ curves.", "要复制并添加 Animator RootT 与 RootQ 曲线的原始 Generic 片段。" },
                { "Root Curves", "根运动曲线" },
                { "Position {0}/3 | Rotation {1}/4", "位置 {0}/3 | 旋转 {1}/4" },
                { "The source clip is missing one or more Root Node channels. Missing channels will use constant values in the generated clip.", "源动画片段缺少一个或多个根节点通道。生成的片段会为缺失通道使用常量值。" },
                { "Assign one source clip to convert.", "请指定一个要转换的源动画片段。" },
                { "Humanoid Animator used to sample the source clip.", "用于采样源动画片段的人形 Animator。" },
                { "Humanoid Avatar used to interpret the source clip. It is filled from the selected Animator, but can be changed manually.", "用于解释源动画片段的人形 Avatar。选择 Animator 后会自动填入，也可手动更改。" },
                { "Animator GameObject or descendant used to resolve and sample source clip Transform bindings.", "用于解析和采样源动画片段 Transform 绑定的 Animator GameObject 或其后代。" },
                { "Generic or raw AnimationClip to convert with the selected Animator and Avatar.", "使用所选 Animator 和 Avatar 转换的 Generic 或原始 AnimationClip。" },
                { "Output", "输出" },
                { "Clip Folder", "片段文件夹" },
                { "Output Suffix", "输出后缀" },
                { "Key Reduction", "关键帧精简" },
                { "Reduce baked Humanoid curve keys within a bounded error after sampling.", "采样完成后，在限定误差范围内减少烘焙的人形动画曲线关键帧。" },
                { "Reduce copied baked curve keys within a bounded error. Object-reference and discrete curves are preserved.", "在限定误差范围内减少复制的烘焙曲线关键帧。对象引用曲线与离散曲线保持不变。" },
                { "Static Curves", "静态曲线" },
                { "Collapse Constant", "折叠恒定曲线" },
                { "Collapse numerically constant Animator curves to one key while keeping every binding.", "将数值上恒定的 Animator 曲线折叠为一个关键帧，同时保留所有绑定。" },
                { "Collapse numerically constant Animator and Transform curves to one key while keeping every binding.", "将数值上恒定的 Animator 与 Transform 曲线折叠为一个关键帧，同时保留所有绑定。" },
                { "Off", "关闭" },
                { "Light", "轻度" },
                { "Medium", "中度" },
                { "Aggressive", "高强度" },
                { "Output Folder", "输出文件夹" },
                { "Browse", "浏览" },
                { "Convert Humanoid Clip", "转换人形动画片段" },
                { "Convert to Humanoid", "转换为人形动画" },
                { "Assign a Humanoid Animator to begin.", "请先指定人形 Animator。" },
                { "Assign a Humanoid Avatar.", "请指定人形 Avatar。" },
                { "The selected Avatar must be valid and Humanoid.", "所选 Avatar 必须有效且为人形。" },
                { "Assign a Root Node.", "请指定根节点。" },
                { "Root Node must be under the Animator hierarchy.", "根节点必须位于 Animator 层级中。" },
                { "Assign a source AnimationClip.", "请指定源 AnimationClip。" },
                { "Ready to convert.", "可以转换。" },
                { "Humanoid conversion failed; see Diagnostics.", "人形动画转换失败；请查看诊断。" },
                { "Converted Humanoid clip with a warning; see Diagnostics.", "已转换人形动画片段，但存在警告；请查看诊断。" },
                { "Converted Humanoid clip.", "已转换人形动画片段。" },
                { "Root Node cannot resolve {0} of {1} Transform paths in the Source Clip. Unresolved curves will be omitted.", "根节点无法解析源动画片段中 {1} 条 Transform 路径里的 {0} 条。未解析的曲线将被省略。" },
                { "Choose an output folder under Assets.", "选择 Assets 下的输出文件夹。" },
                { "Select Humanoid Clip Folder", "选择人形动画片段文件夹" },
                { "Generic -> Humanoid", "Generic -> 人形" },
                { "Choose a folder inside this project's Assets directory.", "请选择此项目 Assets 目录内的文件夹。" },
                { "A Humanoid Animator, a valid Humanoid Avatar, a valid Root Node, and a source AnimationClip are required.", "需要人形 Animator、有效的人形 Avatar、有效的根节点和源 AnimationClip。" },
                { "Humanoid Avatar", "人形 Avatar" },
                { "TriSync Animation", "TriSync 动画" },
                { "Humanoid Clips", "人形动画片段" },
                { "Root Motion", "根运动" },
                { "Target", "目标" },
                { "Use Selected", "使用所选对象" },
                { "Mapping", "映射" },
                { "Auto Map", "自动映射" },
                { "Remap", "重新映射" },
                { "Rebuild all bone assignments from the target hierarchy.", "根据目标层级重新建立全部骨骼分配。" },
                { "Mapping Details", "映射详情" },
                { "Candidate source", "候选来源" },
                { "Valid bones", "有效骨骼" },
                { "Bridge/dummy bones", "桥接/占位骨骼" },
                { "Body", "身体" },
                { "Left Arm", "左臂" },
                { "Right Arm", "右臂" },
                { "Left Leg", "左腿" },
                { "Right Leg", "右腿" },
                { "Left Hand", "左手" },
                { "Right Hand", "右手" },
                { "Head", "头部" },
                { "Hips", "髋部" },
                { "Spine", "脊柱" },
                { "Chest", "胸部" },
                { "Upper Chest", "上胸部" },
                { "Neck", "颈部" },
                { "Left Shoulder", "左肩" },
                { "Right Shoulder", "右肩" },
                { "Left Upper Arm", "左上臂" },
                { "Right Upper Arm", "右上臂" },
                { "Left Lower Arm", "左下臂" },
                { "Right Lower Arm", "右下臂" },
                { "Left Upper Leg", "左大腿" },
                { "Right Upper Leg", "右大腿" },
                { "Left Lower Leg", "左小腿" },
                { "Right Lower Leg", "右小腿" },
                { "Left Foot", "左脚" },
                { "Right Foot", "右脚" },
                { "Left Toes", "左脚趾" },
                { "Right Toes", "右脚趾" },
                { "Left Eye", "左眼" },
                { "Right Eye", "右眼" },
                { "Jaw", "下颌" },
                { "Left Thumb Proximal", "左拇指近端" },
                { "Left Thumb Intermediate", "左拇指中端" },
                { "Left Thumb Distal", "左拇指远端" },
                { "Left Index Proximal", "左食指近端" },
                { "Left Index Intermediate", "左食指中端" },
                { "Left Index Distal", "左食指远端" },
                { "Left Middle Proximal", "左中指近端" },
                { "Left Middle Intermediate", "左中指中端" },
                { "Left Middle Distal", "左中指远端" },
                { "Left Ring Proximal", "左无名指近端" },
                { "Left Ring Intermediate", "左无名指中端" },
                { "Left Ring Distal", "左无名指远端" },
                { "Left Little Proximal", "左小指近端" },
                { "Left Little Intermediate", "左小指中端" },
                { "Left Little Distal", "左小指远端" },
                { "Right Thumb Proximal", "右拇指近端" },
                { "Right Thumb Intermediate", "右拇指中端" },
                { "Right Thumb Distal", "右拇指远端" },
                { "Right Index Proximal", "右食指近端" },
                { "Right Index Intermediate", "右食指中端" },
                { "Right Index Distal", "右食指远端" },
                { "Right Middle Proximal", "右中指近端" },
                { "Right Middle Intermediate", "右中指中端" },
                { "Right Middle Distal", "右中指远端" },
                { "Right Ring Proximal", "右无名指近端" },
                { "Right Ring Intermediate", "右无名指中端" },
                { "Right Ring Distal", "右无名指远端" },
                { "Right Little Proximal", "右小指近端" },
                { "Right Little Intermediate", "右小指中端" },
                { "Right Little Distal", "右小指远端" },
                { "Humanoid Settings", "人形设置" },
                { "Unity HumanDescription twist, stretch, spacing, and translation settings.", "Unity HumanDescription 的扭转、伸展、间距和平移设置。" },
                { "Upper Arm Twist", "上臂扭转" },
                { "Lower Arm Twist", "下臂扭转" },
                { "Upper Leg Twist", "大腿扭转" },
                { "Lower Leg Twist", "小腿扭转" },
                { "Arm Stretch", "手臂伸展" },
                { "Leg Stretch", "腿部伸展" },
                { "Feet Spacing", "双脚间距" },
                { "Translation DoF", "平移自由度" },
                { "Reset Defaults", "恢复默认值" },
                { "Generate Humanoid Avatar", "生成人形 Avatar" },
                { "Create Generic Avatar", "创建 Generic Avatar" },
                { "Motion Root", "运动根节点" },
                { "Variant Suffix", "变体后缀" },
                { "Create Root Motion Clip", "创建根运动动画片段" },
                { "Select Clip Folder", "选择动画片段文件夹" },
                { "Create a copy of Source Clip with Animator RootT and RootQ curves. Root Transform clip settings are not changed automatically.", "创建源动画片段的副本并添加 Animator RootT 与 RootQ 曲线。不会自动更改根变换片段设置。" },
                { "Replace with Generic Avatar", "替换为 Generic Avatar" },
                { "Replace Humanoid Avatar?", "替换人形 Avatar？" },
                { "This Animator currently uses a Humanoid Avatar. Creating a Generic Avatar will replace that assignment.", "此 Animator 当前使用人形 Avatar。创建 Generic Avatar 会替换该指定。" },
                { "Replace", "替换" },
                { "Assign Avatar", "指定 Avatar" },
                { "Assign a Source Clip.", "请指定源动画片段。" },
                { "Ready with constant fallbacks for missing root channels.", "可以创建；缺失的根通道将使用常量回退值。" },
                { "Ready to create a Root Motion Clip.", "可以创建根运动动画片段。" },
                { "Animation Root Motion", "动画根运动" },
                { "Target Animator and a Root Motion Transform under that Animator are required.", "需要目标 Animator 及其层级下的根运动 Transform。" },
                { "BuildGenericAvatar returned null.", "BuildGenericAvatar 返回了 null。" },
                { "Source Clip, Target Animator, and a Root Motion Transform under that Animator are required.", "需要源动画片段、目标 Animator 及其层级下的根运动 Transform。" },
                { "Variant clip asset save failed.", "变体动画片段资源保存失败。" },
                { "Select Folder", "选择文件夹" },
                { "OK", "确定" },
                { "REQ", "必需" },
                { "TriSync Sync Current Pose", "TriSync 同步当前姿态" },
                { "TriSync Sync Shape Keys", "TriSync 同步形态键" },
                { "TriSync Restore Static Pose", "TriSync 恢复静态姿态" },
                { "{0} failed: {1}", "{0}失败：{1}" },
                { "Invalid output folder. Use a Unity asset path under Assets.", "输出文件夹无效。请使用 Assets 下的 Unity 资源路径。" },
                { "Humanoid Avatar Setup", "人形 Avatar 设置" },
                { "Avatar Folder", "Avatar 文件夹" },
                { "Select Avatar Folder", "选择 Avatar 文件夹" },
                { "Mapped bones must be under the Target Animator hierarchy.", "映射的骨骼必须位于目标 Animator 层级中。" },
                { "Not assigned", "未指定" },
                { "Valid", "有效" },
                { "Invalid", "无效" },
                { "Humanoid", "人形" },
                { "Generic", "Generic" },
                { "{0} | {1} | {2}", "{0} | {1} | {2}" },
                { "Required {0}/{1} | Optional {2}/{3}", "必需 {0}/{1} | 可选 {2}/{3}" },
                { "Assign a character Animator to begin.", "请先指定角色 Animator。" },
                { "Humanoid mapping is unavailable.", "人形映射不可用。" },
                { "{0} required bone is missing.", "缺少 {0} 根必需骨骼。" },
                { "{0} required bones are missing.", "缺少 {0} 根必需骨骼。" },
                { "One or more mapped bones are outside the target hierarchy.", "一个或多个映射骨骼位于目标层级之外。" },
                { "Ready to generate and assign a Humanoid Avatar.", "可以生成并指定人形 Avatar。" },
                { "Select a character GameObject or one of its child bones.", "请选择角色 GameObject 或其任一子骨骼。" },
                { "No Animator found on the selection, its parents, or its children.", "在所选对象、其父级或子级中未找到 Animator。" },
                { "Target Animator and all required humanoid bones are required before generating.", "生成前必须指定目标 Animator 和所有必需的人形骨骼。" },
                { "BuildHumanAvatar returned null.", "BuildHumanAvatar 返回了 null。" },
                { "Avatar asset save failed.", "Avatar 资源保存失败。" },
                { "Emission", "自发光" },
                { "Workflow", "工作流" },
                { "Blender Principled / Metallic", "Blender Principled / Metallic" },
                { "Detail Inputs", "细节输入" },
                { "These settings define the surface details by tiling and overlaying additional maps on the surface.", "这些设置通过在表面平铺和叠加附加贴图来定义表面细节。" },
                { "Base Map", "基础贴图" },
                { "Base Color", "基础颜色" },
                { "Blender Principled Base Color texture.", "Blender Principled 基础颜色纹理。" },
                { "Metallic Map", "金属度贴图" },
                { "Blender Principled Metallic texture.", "Blender Principled 金属度纹理。" },
                { "Metallic Channel", "金属度通道" },
                { "Texture channel sampled for metallic. Imported Blender materials set this from the source node graph.", "用于采样金属度的纹理通道。导入的 Blender 材质会根据源节点图设置此项。" },
                { "Metallic", "金属度" },
                { "Roughness Map", "粗糙度贴图" },
                { "Blender Principled Roughness texture. The sampled roughness value is multiplied by Roughness, then converted internally to Unity smoothness.", "Blender Principled 粗糙度纹理。采样值与粗糙度相乘后，在内部转换为 Unity 光滑度。" },
                { "Roughness Channel", "粗糙度通道" },
                { "Texture channel sampled for roughness. Imported Blender materials set this from the source node graph.", "用于采样粗糙度的纹理通道。导入的 Blender 材质会根据源节点图设置此项。" },
                { "Roughness", "粗糙度" },
                { "Occlusion Map", "环境遮蔽贴图" },
                { "Ambient occlusion texture.", "环境遮蔽纹理。" },
                { "Occlusion Strength", "环境遮蔽强度" },
                { "Occlusion Channel", "环境遮蔽通道" },
                { "Texture channel sampled for ambient occlusion. Imported Blender materials set this from the source node graph.", "用于采样环境遮蔽的纹理通道。导入的 Blender 材质会根据源节点图设置此项。" },
                { "Height Map", "高度贴图" },
                { "Height map used for parallax mapping.", "用于视差映射的高度贴图。" },
                { "Height Scale", "高度缩放" },
                { "Height Channel", "高度通道" },
                { "Texture channel sampled for height/parallax. Imported Blender materials set this from the source node graph.", "用于采样高度/视差的纹理通道。导入的 Blender 材质会根据源节点图设置此项。" },
                { "Emission Map", "自发光贴图" },
                { "Emission Color", "自发光颜色" },
                { "Specular Highlights", "高光反射" },
                { "Environment Reflections", "环境反射" },
                { "Workflow Mode", "工作流模式" },
                { "TriSync Principled Lit uses a fixed Blender Principled metallic/roughness workflow.", "TriSync Principled Lit 使用固定的 Blender Principled 金属度/粗糙度工作流。" },
                { "Mask", "遮罩" },
                { "Select a mask for the Detail map. The mask uses the alpha channel of the selected texture. The Tiling and Offset settings have no effect on the mask.", "为细节贴图选择遮罩。遮罩使用所选纹理的 Alpha 通道；平铺和偏移设置不会影响遮罩。" },
                { "Select the surface detail texture.The alpha of your texture determines surface hue and intensity.", "选择表面细节纹理。纹理的 Alpha 决定表面色调和强度。" },
                { "Normal Map", "法线贴图" },
                { "Designates a Normal Map to create the illusion of bumps and dents in the details of this Material's surface.", "指定法线贴图，在材质表面细节中模拟凹凸。" },
                { "Setting the scaling factor to a value other than 1 results in a less performant shader variant.", "将缩放系数设为 1 以外的值会使用性能较低的着色器变体。" },
                { "This texture is not in linear space.", "此纹理不在线性空间中。" },
            };

        public static BlenderSyncLanguage Language
        {
            get
            {
                var stored = EditorPrefs.GetInt(LanguageEditorPrefKey, (int)BlenderSyncLanguage.System);
                return Enum.IsDefined(typeof(BlenderSyncLanguage), stored)
                    ? (BlenderSyncLanguage)stored
                    : BlenderSyncLanguage.System;
            }
            set
            {
                var normalized = Enum.IsDefined(typeof(BlenderSyncLanguage), value)
                    ? value
                    : BlenderSyncLanguage.System;
                EditorPrefs.SetInt(LanguageEditorPrefKey, (int)normalized);
                InternalEditorUtility.RepaintAllViews();
            }
        }

        public static string Tr(string source)
        {
            return TranslateForLanguage(
                source,
                ResolveLanguage(Language, Application.systemLanguage));
        }

        public static string Format(string source, params object[] args)
        {
            return FormatForLanguage(
                source,
                ResolveLanguage(Language, Application.systemLanguage),
                args);
        }

        public static string FormatForLanguage(
            string source,
            BlenderSyncLanguage language,
            params object[] args)
        {
            return string.Format(
                CultureInfo.CurrentCulture,
                TranslateForLanguage(source, language),
                args ?? Array.Empty<object>());
        }

        public static string TranslateForLanguage(string source, BlenderSyncLanguage language)
        {
            if (string.IsNullOrEmpty(source) || language != BlenderSyncLanguage.SimplifiedChinese)
                return source ?? string.Empty;
            return SimplifiedChinese.TryGetValue(source, out var translated) ? translated : source;
        }

        public static BlenderSyncLanguage ResolveLanguage(
            BlenderSyncLanguage preference,
            SystemLanguage systemLanguage)
        {
            if (preference != BlenderSyncLanguage.System)
                return preference;
            return systemLanguage == SystemLanguage.ChineseSimplified
                ? BlenderSyncLanguage.SimplifiedChinese
                : BlenderSyncLanguage.English;
        }

        internal static string[] LanguageLabels()
        {
            return new[] { Tr("System"), Tr("English"), Tr("Simplified Chinese") };
        }

    }
}
#endif
